package interfaceG;

import javax.swing.JOptionPane;
import java.lang.String;

//@LucasTavares
public class CadastroJogadorJFrame extends javax.swing.JFrame {
    
    private VisualizarJFrame telaVisualizar;
    /**
     * Creates new form CadastroJogadorJFrame
     */
    public CadastroJogadorJFrame(VisualizarJFrame telaVisualizar) {
        initComponents();
        this.telaVisualizar = telaVisualizar;
    }
 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campo2Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoSalario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoModalidade = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        campoPremio = new javax.swing.JTextField();
        campoIdade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Idade:");

        campo2Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo2NomeKeyTyped(evt);
            }
        });

        jLabel3.setText("Salário:");

        campoSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoSalarioKeyTyped(evt);
            }
        });

        jLabel4.setText("Prêmio Individual:");

        jLabel5.setText("Modalidade:");

        campoModalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoModalidadeKeyReleased(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        campoPremio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPremioKeyTyped(evt);
            }
        });

        campoIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoIdadeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(btVoltar)
                                .addGap(84, 84, 84)
                                .addComponent(btCadastrar))
                            .addComponent(jLabel1)
                            .addComponent(campoPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(campoModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo2Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(campoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(campoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(campo2Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPremio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btVoltar)
                    .addComponent(btCadastrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparCampos();
  
    }//GEN-LAST:event_btLimparActionPerformed
           private void limparCampos() {
                campo2Nome.setText("");
                campoIdade.setText("");
                campoSalario.setText("");
                campoPremio.setText("");
                campoModalidade.setText("");
    }
            public void mostrarJogador(Jogador j){
                
                this.campo2Nome.setText(j.getnome());
                this.campoIdade.setText(Integer.toString(j.getidade()));
                this.campoSalario.setText(Double.toString(j.getsalario()));
                this.campoPremio.setText(j.getpremioIndividual());
                this.campoModalidade.setText(j.getmodalidade());
                desabilitarCampos();
                this.setVisible(true);
    }
    
            public void desabilitarCampos()
    {
                this.campo2Nome.setEnabled(false);
                this.campoIdade.setEnabled(false);
                this.campoSalario.setEnabled(false);
                this.campoPremio.setEnabled(false);
                this.campoModalidade.setEnabled(false);
                this.btCadastrar.setEnabled(false);
                this.btLimpar.setEnabled(false);
                
    }
    
            public void habilitarCampos(){
                this.campo2Nome.setEnabled(true);
                this.campoIdade.setEnabled(true);
                this.campoSalario.setEnabled(true);
                this.campoPremio.setEnabled(true);
                this.campoModalidade.setEnabled(true);
                this.btCadastrar.setEnabled(true);
                this.btLimpar.setEnabled(true);
    }
    
    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
                Jogador j = new Jogador();
                j.setnome(campo2Nome.getText());
                j.setidade(Integer.parseInt(campoIdade.getText()));
                j.setsalario(Double.parseDouble(campoSalario.getText()));
                j.setpremioIndividual(campoPremio.getText());
                j.setmodalidade(campoModalidade.getText());
                this.telaVisualizar.addJogador(j);
                JOptionPane.showMessageDialog(this, "Cadastrado realizado "
                 + "com sucesso!","Sucesso",JOptionPane.INFORMATION_MESSAGE);
                this.limparCampos();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
            this.setVisible(false);
            this.telaVisualizar.setVisible(true);
            this.habilitarCampos();
            limparCampos();      
        
    }//GEN-LAST:event_btVoltarActionPerformed

    
    private void campoIdadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIdadeKeyTyped

    }//GEN-LAST:event_campoIdadeKeyTyped

    private void campoSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoSalarioKeyTyped

    }//GEN-LAST:event_campoSalarioKeyTyped

    private void campo2NomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo2NomeKeyTyped

    }//GEN-LAST:event_campo2NomeKeyTyped

    private void campoPremioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPremioKeyTyped
      
    }//GEN-LAST:event_campoPremioKeyTyped

    private void campoModalidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoModalidadeKeyReleased

    }//GEN-LAST:event_campoModalidadeKeyReleased
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField campo2Nome;
    private javax.swing.JTextField campoIdade;
    private javax.swing.JTextField campoModalidade;
    private javax.swing.JTextField campoPremio;
    private javax.swing.JTextField campoSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}