
package interfaceG;
//@LucasTavares

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

public class VisualizarJFrame extends javax.swing.JFrame {

    //referenciar a tela de cadastro
    private CadastroJogadorJFrame telaCadastro;
    
    //salvar os dados do jogador 
    private ArrayList<Jogador> array;

    public VisualizarJFrame() {
        initComponents();
        //inicializa a tela de cadastro e visualizar
        telaCadastro =  new CadastroJogadorJFrame(this);
        
        this.array = new ArrayList<Jogador>();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaJogadores = new javax.swing.JTable();
        btIncluir = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btVisualizar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaJogadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Idade", "Salário", "Prêmio Individual", "Modalidade"
            }
        ));
        jScrollPane1.setViewportView(tabelaJogadores);

        btIncluir.setText("Inserir");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btVisualizar.setText("Visualizar");
        btVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarActionPerformed(evt);
            }
        });

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btRemover)
                        .addGap(18, 18, 18)
                        .addComponent(btFechar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btIncluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIncluir)
                    .addComponent(btRemover)
                    .addComponent(btVisualizar)
                    .addComponent(btFechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarActionPerformed
          
        int linhaSelecionda = tabelaJogadores.getSelectedRow();
                
        if (linhaSelecionda < 0){
            JOptionPane.showMessageDialog(this, "Por Favor, Selecione uma linha!"
                    + "", "Aviso", JOptionPane.WARNING_MESSAGE);
        }else{
            this.telaCadastro.mostrarJogador(array.get(linhaSelecionda));
            this.setVisible(false);
        }
    }//GEN-LAST:event_btVisualizarActionPerformed

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        //torna a outra tela visível
            this.telaCadastro.setVisible(true);
            
            //torna esta tela invisível
            this.setVisible(false);
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
    
        int selectedIndex = tabelaJogadores.getSelectedRow();
        
        if (selectedIndex < 0){
            //erro se nenhuma linha for selecionada
            JOptionPane.showMessageDialog(this, "Por Favor, Selecione um item!","Aviso",JOptionPane.WARNING_MESSAGE);
        }else{
            //um item está selecionado, então remove
            this.removeJogador(selectedIndex);        
    }//GEN-LAST:event_btRemoverActionPerformed
    }
    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_btFecharActionPerformed
    
    
    public void addJogador(Jogador j){
        this.array.add(j);
        this.addJogadorToTable(j);
    }
    
     public void addJogadorToTable(Jogador j){
        DefaultTableModel model = (DefaultTableModel)tabelaJogadores.getModel();
        model.addRow(new Object[]{j.getnome(), j.getidade(), j.getsalario(), j.getpremioIndividual(), j.getmodalidade()});
    }
      public void removeJogador(int i) {
                array.remove(i);
        removeJogadorFromTable(i);
    }
         
    public void removeJogadorFromTable(int i){
        DefaultTableModel model = (DefaultTableModel)tabelaJogadores.getModel();
        model.removeRow(i);
    }
    
    public void redesenhaTabela(){
        DefaultTableModel model = (DefaultTableModel)tabelaJogadores.getModel();
        while (model.getRowCount() > 0){
            model.removeRow(0);
        }
        
        for (Jogador j : array){
            model.addRow(new Object[]{j.getnome(), j.getidade(), j.getsalario(), j.getpremioIndividual(), j.getmodalidade()});
        }
    }
       
     /**
     * @param args the command line arguments
     */
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaJogadores;
    // End of variables declaration//GEN-END:variables


   
}
